---
action: 1
amt: 1
currency_code: 414
lang_id: USA
response_url: http://www.aalhamad.com
error_url: http://www.aalhamad.com
track_id: 1
resource_path: ./resource/
input_file_name: resource.cgn
alias: twseel.xml